apiVersion: batch/v1
kind: Job
metadata:
  # generate random names
  generateName: kube-job-
  labels:
    jobgroup: jobexample
spec:
  # multiple jobs and parallelism
  completions: 6
  parallelism: 2
  template:
    metadata:
      name: kubejob
      labels:
        jobgroup: jobexample
    spec:
      containers:
        - name: c
          image: devopscube/kubernetes-job-demo:latest
          args: ['30']
      restartPolicy: OnFailure
